version: '3'
services:
    web:
        # restart: always
        build: .
        depends_on:
        - postgres
        links:
        - "postgres:postgres"
        volumes:
        - .:/project_flask_card
        env_file: .env
        environment:
        - MODE
        - POSTGRES_HOST=postgres
        ports:
        - "8000:8000"
        command: flask run
    
    postgres:
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      image: postgres:latest
      ports:
        - "5432:5432"
      restart: always
      volumes:
        - ./postgres-data:/var/lib/postgresql/data