"""right/wrong answers in collection

Revision ID: 42d0260f6216
Revises: ffa1822d2bff
Create Date: 2020-05-06 14:42:07.247181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42d0260f6216"
down_revision = "ffa1822d2bff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("collection", sa.Column("right_answer", sa.Integer(), nullable=True))
    op.add_column("collection", sa.Column("wrong_answer", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "wrong_answer")
    op.drop_column("collection", "right_answer")
    # ### end Alembic commands ###
