"""Add category

Revision ID: adb8551fc20f
Revises: 5059405af9aa
Create Date: 2020-04-20 15:12:42.216292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "adb8551fc20f"
down_revision = "5059405af9aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_category_name"), "category", ["name"], unique=False)
    op.add_column("collection", sa.Column("category_id", sa.Integer(), nullable=True))
    op.add_column("collection", sa.Column("description", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_collection_description"), "collection", ["description"], unique=False
    )
    op.drop_index("ix_collection_category", table_name="collection")
    op.create_foreign_key(None, "collection", "category", ["category_id"], ["id"])
    op.drop_column("collection", "category")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column(
            "category", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "collection", type_="foreignkey")
    op.create_index("ix_collection_category", "collection", ["category"], unique=False)
    op.drop_index(op.f("ix_collection_description"), table_name="collection")
    op.drop_column("collection", "description")
    op.drop_column("collection", "category_id")
    op.drop_index(op.f("ix_category_name"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
