"""remove flashcard column

Revision ID: ee9a5cae3684
Revises: adb8551fc20f
Create Date: 2020-04-23 13:24:12.309505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9a5cae3684'
down_revision = 'adb8551fc20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcard', 'wrong_answered')
    op.drop_column('flashcard', 'right_answered')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcard', sa.Column('right_answered', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('flashcard', sa.Column('wrong_answered', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
