"""Add answer input type

Revision ID: ffa1822d2bff
Revises: ee9a5cae3684
Create Date: 2020-05-04 23:10:49.697039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ffa1822d2bff"
down_revision = "ee9a5cae3684"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flashcard", sa.Column("input_type", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flashcard", "input_type")
    # ### end Alembic commands ###
